name: Pull Request
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: |
          npm install
          npm bootstrap

      # - name: Bootstrap
      #   run: npm run lerna bootstrap

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

      - name: Publish
        run: npm run lerna publish prerelease -- --no-push --no-git-tag-version --preid ${{ github.head_ref }}
