name: Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pr-build-test:
    name: Pull Request Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: npm install

      - name: Bootstrap
        run: npm run lerna bootstrap

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: coverage
